version: '3.8'
services:
  database-dev:
    image: postgres:17.2-alpine
    container_name: credit_score_local_dev
    environment:
      POSTGRES_USER: wildrimak
      POSTGRES_PASSWORD: dificil
      POSTGRES_DB: credit-score-dev
    ports:
      - "5432:5432"
