spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-score-dev
    platform: postgres
    username: wildrimak
    password: dificil
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate